name: Build and Deploy to Vercel

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dune developer preview
        run: |
          curl -fsSL https://get.dune.build/install | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Setup Dune environment
        run: |
          dune pkg lock

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install JS dependencies
        run: bun install

      - name: Build OCaml
        run: dune build --profile=release

      - name: Build Vite
        run: bun run build


      - name: Copy vercel.json
        run: cp vercel.json dist/

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy to Vercel
        run: |
          vercel deploy ./dist --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
